services:
  seerr:
    image: fallenbagel/jellyseerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
      - PORT=5055 #optional
    networks:
      - cn1
    ports:
      - 5055:5055
    volumes:
      - /home/kyle/appdata/seerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.seerr-rtr.tls=true
      - traefik.http.routers.seerr-rtr.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.seerr-rtr.entrypoints=https
      - traefik.http.services.seerr-svc.loadbalancer.server.port=5055
networks:
  cn1:
    external: true