services:
  scrypted:
    environment:
      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer
        ${WATCHTOWER_HTTP_API_TOKEN:-env_missing_fallback}
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update
    image: ghcr.io/koush/scrypted
    volumes:
      - ./volume:/server/volume
    devices:
      - "/dev/dri:/dev/dri"
    container_name: scrypted
    restart: unless-stopped
    network_mode: host
    logging:
      driver: none
    labels:
      - com.centurylinklabs.watchtower.scope=scrypted
  watchtower:
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN:-env_missing_fallback}
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_SCOPE=scrypted
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=${WATCHTOWER_HTTP_API_PERIODIC_POLLS:-true}
    image: containrrr/watchtower
    container_name: scrypted-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.scope=scrypted
    ports:
      - 10444:8080
    command: --interval 3600 --cleanup --scope scrypted
networks: {}
