services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 8187:80
            - 8447:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=${SPEEDTEST_APP_KEY}
            - DB_CONNECTION=sqlite
        volumes:
            - /home/kyle/appdata/speedtest/data:/config
            - /home/kyle/appdata/speedtest/keys:/config/keys
