services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3080:8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - webui:/app/data
    networks:
      cn1:
    labels:
      - traefik.enable=true
      - traefik.http.routers.openwebui-rtr.tls=true
      - traefik.http.routers.openwebui-rtr.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.openwebui-rtr.entrypoints=https
      - traefik.http.services.openwebui-svc.loadbalancer.server.port=8080
volumes:
  webui:
networks:
  cn1:
    external: true