services:
  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3080:8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - webui:/app/data
    networks:
      cn1:
volumes:
  webui:
networks:
  cn1:
    external: true